FROM public.ecr.aws/docker/library/node:18

WORKDIR /app

# Copy package files
COPY package*.json ./
COPY nest-cli.json ./
COPY tsconfig.build.json ./
COPY tsconfig.json ./

# Install all dependencies (including dev dependencies)
RUN npm install

# Expose port
EXPOSE 3000

# Start the application in development mode
CMD [ "npm", "run", "start:dev" ]

